# Generated by Django 4.2 on 2023-06-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=123)),
                ('tel', models.CharField(max_length=123)),
                ('location', models.CharField(max_length=123)),
                ('food', models.CharField(max_length=123)),
                ('many', models.CharField(max_length=123)),
                ('check1', models.CharField(max_length=123)),
            ],
        ),
    ]
