# Generated by Django 4.2 on 2023-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homemodel_check2_homemodel_check3_homemodel_check4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='food3',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
